import type { Metadata } from "next";
import { SanityLive } from "@/sanity/lib/live";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider } from "@/components/providers/sidebar-provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DashboardLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider>
            <SidebarProvider>
                <div className="h-full">{children}</div>
            </SidebarProvider>

            <SanityLive />
        </ClerkProvider>
    );
}